package io.github.jaruizes.proposal.infrastructure.persistence;

import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import io.github.jaruizes.proposal.domain.model.*; import io.github.jaruizes.proposal.infrastructure.persistence.entity.*; import java.util.*;
final class PersistenceMapper { static final ObjectMapper JSON=new ObjectMapper();
 static OfferJpaEntity toEntity(Offer o){var e=new OfferJpaEntity();e.setId(o.id());e.setName(o.name());e.setCustomer(o.customer());e.setLanguage(o.language());e.setPresentationLanguage(o.presentationLanguage());e.setInputDriveFolder(o.inputDriveFolder());e.setOutputDriveFolder(o.outputDriveFolder());e.setPresentationName(o.presentationName());e.setPresentationTemplateId(o.presentationTemplateId());e.setProposalTemplateId(o.proposalTemplateId());e.setGeneratePresentation(o.generatePresentation());e.setAiProvider(o.aiProvider());try{e.setModelsJson(JSON.writeValueAsString(o.models()));e.setProposalGuidanceJson(JSON.writeValueAsString(o.proposalGuidance()));e.setPresentationGuidanceJson(JSON.writeValueAsString(o.presentationGuidance()));}catch(Exception ex){throw new IllegalStateException(ex);}e.setCurrentPhase(o.currentPhase().name());e.setStatus(o.status().name());e.setCreatedAt(o.createdAt());e.setUpdatedAt(o.updatedAt());return e;}
 static Offer toDomain(OfferJpaEntity e){try{Map<String,String> models=JSON.readValue(e.getModelsJson(),new TypeReference<>(){});Object proposalGuidance=e.getProposalGuidanceJson()==null?null:JSON.readValue(e.getProposalGuidanceJson(),Object.class);Object guidance=e.getPresentationGuidanceJson()==null?null:JSON.readValue(e.getPresentationGuidanceJson(),Object.class);return new Offer(e.getId(),e.getName(),e.getCustomer(),e.getLanguage(),e.getPresentationLanguage(),e.getInputDriveFolder(),e.getOutputDriveFolder(),e.getPresentationName(),e.getPresentationTemplateId(),e.getProposalTemplateId(),e.isGeneratePresentation(),e.getAiProvider(),models,proposalGuidance,guidance,PhaseType.valueOf(e.getCurrentPhase()),ExecutionStatus.valueOf(e.getStatus()),e.getCreatedAt(),e.getUpdatedAt());}catch(Exception ex){throw new IllegalStateException(ex);}}
 static PhaseJpaEntity toEntity(PhaseExecution p){var e=new PhaseJpaEntity();e.setId(p.id());e.setOfferId(p.offerId());e.setPhase(p.phase().name());e.setStatus(p.status().name());e.setVersion(p.version());e.setErrorMessage(p.errorMessage());e.setStartedAt(p.startedAt());e.setCompletedAt(p.completedAt());return e;} static PhaseExecution toDomain(PhaseJpaEntity e){return new PhaseExecution(e.getId(),e.getOfferId(),PhaseType.valueOf(e.getPhase()),ExecutionStatus.valueOf(e.getStatus()),e.getVersion(),e.getErrorMessage(),e.getStartedAt(),e.getCompletedAt());}
 static ArtifactJpaEntity toEntity(Artifact a){var e=new ArtifactJpaEntity();e.setId(a.id());e.setOfferId(a.offerId());e.setPhase(a.phase().name());e.setType(a.type().name());e.setVersion(a.version());e.setContent(a.content());e.setCreatedAt(a.createdAt());return e;} static Artifact toDomain(ArtifactJpaEntity e){return new Artifact(e.getId(),e.getOfferId(),PhaseType.valueOf(e.getPhase()),ArtifactType.valueOf(e.getType()),e.getVersion(),e.getContent(),e.getCreatedAt());}
 static AgentExecutionJpaEntity toEntity(AgentExecution a){var e=new AgentExecutionJpaEntity();e.setId(a.id());e.setOfferId(a.offerId());e.setPhase(a.phase().name());e.setAgentKey(a.agentKey());e.setStatus(a.status().name());e.setObjective(a.objective());e.setOutput(a.output());e.setModel(a.model());e.setInputTokens(a.inputTokens());e.setOutputTokens(a.outputTokens());e.setProviderRequestId(a.providerRequestId());e.setStartedAt(a.startedAt());e.setCompletedAt(a.completedAt());e.setErrorMessage(a.errorMessage());return e;} static AgentExecution toDomain(AgentExecutionJpaEntity e){return new AgentExecution(e.getId(),e.getOfferId(),PhaseType.valueOf(e.getPhase()),e.getAgentKey(),AgentTaskStatus.valueOf(e.getStatus()),e.getObjective(),e.getOutput(),e.getModel(),e.getInputTokens(),e.getOutputTokens(),e.getProviderRequestId(),e.getStartedAt(),e.getCompletedAt(),e.getErrorMessage());}
}
