package io.github.jaruizes.proposal.domain.model;

public enum ArtifactType {
    SOURCE_MANIFEST,
    SOURCE_CONTEXT,
    SOURCE_INGESTION_REPORT,
    OPPORTUNITY_BRIEF,
    QUESTIONS,
    TECHNOLOGY,
    STRATEGY,
    SOLUTION,
    SOLUTION_PLAN,
    SLIDES_PLAN,
    PRESENTATION_METADATA,
    PRESENTATION_BUILD_REPORT
}
