package io.github.jaruizes.proposal.business;

import io.github.jaruizes.proposal.domain.model.*; import io.github.jaruizes.proposal.domain.ports.*; import org.springframework.stereotype.Service; import java.time.Instant; import java.util.*; import java.util.concurrent.*;
@Service public class AgentRuntimeService {
 private final AgentRegistryService registry; private final PromptService prompts; private final LlmProviderPort llm; private final AgentExecutionRepositoryPort executions;
 public AgentRuntimeService(AgentRegistryService r,PromptService p,LlmProviderPort l,AgentExecutionRepositoryPort e){registry=r;prompts=p;llm=l;executions=e;}
 public LlmResult execute(AgentTask task,String model,String context){var d=registry.get(task.agentKey());var started=Instant.now();var id=UUID.randomUUID();executions.save(new AgentExecution(id,task.offerId(),task.phase(),task.agentKey(),AgentTaskStatus.RUNNING,task.objective(),null,model,0,0,null,started,null,null));try{var system=prompts.load(d.promptResource());var result=llm.execute(new LlmRequest(model,system,List.of(new LlmRequest.Message("user",task.prompt()+"\n\n## Contexto disponible\n"+context)),12000));executions.save(new AgentExecution(id,task.offerId(),task.phase(),task.agentKey(),AgentTaskStatus.COMPLETED,task.objective(),result.content(),result.model(),result.inputTokens(),result.outputTokens(),result.requestId(),started,Instant.now(),null));return result;}catch(RuntimeException ex){executions.save(new AgentExecution(id,task.offerId(),task.phase(),task.agentKey(),AgentTaskStatus.FAILED,task.objective(),null,model,0,0,null,started,Instant.now(),ex.getMessage()));throw ex;}}
 public List<LlmResult> executeParallel(List<AgentTask> tasks,String model,String context){try(var executor=Executors.newVirtualThreadPerTaskExecutor()){var fs=tasks.stream().map(t->CompletableFuture.supplyAsync(()->execute(t,model,context),executor)).toList();return fs.stream().map(CompletableFuture::join).toList();}}
}
