package io.github.jaruizes.proposal.business;

import io.github.jaruizes.proposal.domain.exceptions.DomainException;
import io.github.jaruizes.proposal.domain.model.*;
import io.github.jaruizes.proposal.domain.ports.*;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.core.task.TaskExecutor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;

import java.time.Instant;
import java.util.*;

@Service
public class OfferWorkflowService {
    private final OfferRepositoryPort offers; private final PhaseRepositoryPort phases; private final ArtifactRepositoryPort artifacts; private final AgentExecutionRepositoryPort agentExecutions; private final AgentRuntimeService agents; private final PresentationPort presentations; private final SlidePlanValidator slidePlanValidator; private final TaskExecutor phaseTaskExecutor;
    public OfferWorkflowService(OfferRepositoryPort offers,PhaseRepositoryPort phases,ArtifactRepositoryPort artifacts,AgentExecutionRepositoryPort agentExecutions,AgentRuntimeService agents,PresentationPort presentations,SlidePlanValidator slidePlanValidator,@Qualifier("agentTaskExecutor") TaskExecutor phaseTaskExecutor){this.offers=offers;this.phases=phases;this.artifacts=artifacts;this.agentExecutions=agentExecutions;this.agents=agents;this.presentations=presentations;this.slidePlanValidator=slidePlanValidator;this.phaseTaskExecutor=phaseTaskExecutor;}

    @Transactional public Offer create(CreateOfferCommand command){var now=Instant.now();var offer=new Offer(UUID.randomUUID(),command.name(),command.customer(),command.language(),command.presentationLanguage(),command.inputDriveFolder(),command.outputDriveFolder(),command.presentationName(),command.aiProvider(),command.models(),command.presentationGuidance(),PhaseType.ANALYSIS,ExecutionStatus.RUNNING,now,now);offer=offers.save(offer);for(var phase:PhaseType.values())phases.save(new PhaseExecution(UUID.randomUUID(),offer.id(),phase,phase==PhaseType.ANALYSIS?ExecutionStatus.RUNNING:ExecutionStatus.NOT_STARTED,1,null,phase==PhaseType.ANALYSIS?now:null,null));submitPhase(offer.id(),PhaseType.ANALYSIS,null);return offer;}
    public List<Offer> findAll(){return offers.findAll();} public Offer find(UUID id){return offers.findById(id).orElseThrow(()->new DomainException("Offer not found"));} public List<PhaseExecution> phases(UUID id){return phases.findByOfferId(id);} public List<Artifact> artifacts(UUID id){return artifacts.findByOfferId(id);} public List<AgentExecution> agentExecutions(UUID id){return agentExecutions.findByOfferId(id);}

    @Transactional public void approve(UUID offerId,PhaseType phaseType){var phase=phases.find(offerId,phaseType).orElseThrow(()->new DomainException("Phase not found"));if(phase.status()!=ExecutionStatus.WAITING_FOR_HUMAN)throw new DomainException("Phase is not waiting for approval");phases.save(new PhaseExecution(phase.id(),offerId,phaseType,ExecutionStatus.APPROVED,phase.version(),null,phase.startedAt(),Instant.now()));var offer=find(offerId);var next=phaseType.next();if(next==null){offers.save(copyOffer(offer,phaseType,ExecutionStatus.APPROVED));return;}var n=phases.find(offerId,next).orElseThrow();phases.save(new PhaseExecution(n.id(),offerId,next,ExecutionStatus.RUNNING,n.version(),null,Instant.now(),null));offers.save(copyOffer(offer,next,ExecutionStatus.RUNNING));submitPhase(offerId,next,null);}
    @Transactional public void refine(UUID offerId,PhaseType phaseType,String instruction){var phase=phases.find(offerId,phaseType).orElseThrow(()->new DomainException("Phase not found"));if(phase.status()==ExecutionStatus.RUNNING)throw new DomainException("Phase is already running");invalidateDownstream(offerId,phaseType);phases.save(new PhaseExecution(phase.id(),offerId,phaseType,ExecutionStatus.RUNNING,phase.version()+1,null,Instant.now(),null));offers.save(copyOffer(find(offerId),phaseType,ExecutionStatus.RUNNING));submitPhase(offerId,phaseType,instruction);}
    private void invalidateDownstream(UUID offerId,PhaseType from){var current=from.next();while(current!=null){var p=phases.find(offerId,current).orElseThrow();phases.save(new PhaseExecution(p.id(),offerId,current,p.status()==ExecutionStatus.NOT_STARTED?ExecutionStatus.NOT_STARTED:ExecutionStatus.STALE,p.version(),null,p.startedAt(),p.completedAt()));current=current.next();}}
    private void submitPhase(UUID offerId,PhaseType phaseType,String refinement){Runnable task=()->phaseTaskExecutor.execute(()->runPhase(offerId,phaseType,refinement));if(TransactionSynchronizationManager.isSynchronizationActive())TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){@Override public void afterCommit(){task.run();}});else task.run();}
    private void runPhase(UUID offerId,PhaseType phaseType,String refinement){try{var offer=find(offerId);switch(phaseType){case ANALYSIS->runAnalysis(offer,refinement);case STRATEGY->runStrategy(offer,refinement);case SOLUTION->runSolution(offer,refinement);case SLIDE_PLAN->runSlidePlan(offer,refinement);case PRESENTATION->runPresentation(offer);}markWaiting(offerId,phaseType);}catch(Exception e){markFailed(offerId,phaseType,e);}}

    private void runAnalysis(Offer offer,String refinement){var prompt="Ejecuta la fase 1 de Proposal Copilot. Produce un único bloque JSON con las claves opportunityBrief (markdown requerido), questions (markdown o null), technology (markdown o null). Revisa la información disponible, separa FACT/INFERENCE/ASSUMPTION/QUESTION y no diseñes todavía la solución."+refinement(refinement);var result=agents.execute(AgentTask.of(offer.id(),PhaseType.ANALYSIS,"business-analyst","Entender y cualificar la oportunidad",prompt),model(offer,"analysis"),offerContext(offer));var parsed=JsonFragments.parse(result.content());saveArtifact(offer.id(),PhaseType.ANALYSIS,ArtifactType.OPPORTUNITY_BRIEF,parsed.getOrDefault("opportunityBrief",result.content()));if(parsed.get("questions")!=null)saveArtifact(offer.id(),PhaseType.ANALYSIS,ArtifactType.QUESTIONS,parsed.get("questions"));if(parsed.get("technology")!=null)saveArtifact(offer.id(),PhaseType.ANALYSIS,ArtifactType.TECHNOLOGY,parsed.get("technology"));}
    private void runStrategy(Offer offer,String refinement){var context=approvedArtifactsContext(offer.id(),List.of(ArtifactType.OPPORTUNITY_BRIEF,ArtifactType.QUESTIONS,ArtifactType.TECHNOLOGY));var result=agents.execute(AgentTask.of(offer.id(),PhaseType.STRATEGY,"business-analyst","Construir estrategia de respuesta","Genera strategy.md. No hagas arquitectura detallada, estimaciones, staffing, duración, precio ni slides."+refinement(refinement)),model(offer,"strategy"),offerContext(offer)+context);saveArtifact(offer.id(),PhaseType.STRATEGY,ArtifactType.STRATEGY,result.content());}
    private void runSolution(Offer offer,String refinement){var base=offerContext(offer)+approvedArtifactsContext(offer.id(),List.of(ArtifactType.OPPORTUNITY_BRIEF,ArtifactType.QUESTIONS,ArtifactType.TECHNOLOGY,ArtifactType.STRATEGY));var architect=agents.execute(AgentTask.of(offer.id(),PhaseType.SOLUTION,"solution-architect","Definir solución propuesta","Genera solution.md siguiendo el contrato de Proposal Copilot. No estimes esfuerzo, duración, staffing ni precio."+refinement(refinement)),model(offer,"solutionArchitecture"),base);saveArtifact(offer.id(),PhaseType.SOLUTION,ArtifactType.SOLUTION,architect.content());var delivery=agents.execute(AgentTask.of(offer.id(),PhaseType.SOLUTION,"delivery-manager","Definir enfoque de ejecución","Genera solution-plan.md como WBS de alto nivel NO estimado. Incluye cobertura capability→workstream."),model(offer,"deliveryPlanning"),base+"\n\n## solution.md\n"+architect.content());saveArtifact(offer.id(),PhaseType.SOLUTION,ArtifactType.SOLUTION_PLAN,delivery.content());agents.execute(AgentTask.of(offer.id(),PhaseType.SOLUTION,"business-analyst","Revisión de coherencia","Revisa coherencia entre strategy, solution y solution-plan. Devuelve una revisión concisa. No crees un nuevo artefacto canónico."),model(offer,"solutionArchitecture"),base+"\n\n## solution.md\n"+architect.content()+"\n\n## solution-plan.md\n"+delivery.content());}
    private void runSlidePlan(Offer offer,String refinement){var context=approvedArtifactsContext(offer.id(),List.of(ArtifactType.OPPORTUNITY_BRIEF,ArtifactType.STRATEGY,ArtifactType.SOLUTION,ArtifactType.SOLUTION_PLAN));var prompt="Genera slides-plan.md jerárquico con SECTION y SUBSECTION explícitos. Cada slide debe incluir exactamente '### Título de slide'. Títulos: objetivo <=10 palabras, máximo absoluto 12. No uses cliente/customer en copy visible: usa el nombre real de la organización o omite la referencia. Cada sección/subsección debe declarar título exacto y si tiene portada. max_slides es soft limit y sólo cuenta slides de contenido."+refinement(refinement);var result=agents.execute(AgentTask.of(offer.id(),PhaseType.SLIDE_PLAN,"business-analyst","Planificar narrativa de presentación",prompt),model(offer,"slidePlanning"),offerContext(offer)+"\n\n## Presentation guidance\n"+offer.presentationGuidance()+context);slidePlanValidator.validate(result.content());saveArtifact(offer.id(),PhaseType.SLIDE_PLAN,ArtifactType.SLIDES_PLAN,result.content());}
    private void runPresentation(Offer offer){var plan=artifacts.findLatest(offer.id(),ArtifactType.SLIDES_PLAN).orElseThrow(()->new DomainException("Missing approved slides-plan"));slidePlanValidator.validate(plan.content());var result=presentations.materialize(offer.id(),plan.content(),offer.outputDriveFolder(),offer.presentationName());saveArtifact(offer.id(),PhaseType.PRESENTATION,ArtifactType.PRESENTATION_METADATA,"{\"externalId\":\""+result.externalId()+"\",\"url\":\""+result.url()+"\"}");saveArtifact(offer.id(),PhaseType.PRESENTATION,ArtifactType.PRESENTATION_BUILD_REPORT,result.buildReport());}

    private void saveArtifact(UUID offerId,PhaseType phase,ArtifactType type,String content){artifacts.save(new Artifact(UUID.randomUUID(),offerId,phase,type,artifacts.nextVersion(offerId,type),content,Instant.now()));}
    private String approvedArtifactsContext(UUID offerId,List<ArtifactType> types){var b=new StringBuilder();for(var t:types)artifacts.findLatest(offerId,t).ifPresent(a->b.append("\n\n## ").append(t).append("\n").append(a.content()));return b.toString();}
    private String offerContext(Offer o){return "Offer name: %s\nOrganization: %s\nLanguage: %s\nPresentation language: %s\nGoogle Drive input folder: %s\n".formatted(o.name(),o.customer(),o.language(),o.presentationLanguage(),o.inputDriveFolder());}
    private String model(Offer offer,String key){return offer.models().getOrDefault(key,"claude-sonnet-4-6");} private String refinement(String r){return r==null?"":"\nHuman refinement: "+r;}
    private void markWaiting(UUID offerId,PhaseType type){var p=phases.find(offerId,type).orElseThrow();phases.save(new PhaseExecution(p.id(),offerId,type,ExecutionStatus.WAITING_FOR_HUMAN,p.version(),null,p.startedAt(),Instant.now()));offers.save(copyOffer(find(offerId),type,ExecutionStatus.WAITING_FOR_HUMAN));}
    private void markFailed(UUID offerId,PhaseType type,Exception e){var p=phases.find(offerId,type).orElseThrow();phases.save(new PhaseExecution(p.id(),offerId,type,ExecutionStatus.FAILED,p.version(),e.getMessage(),p.startedAt(),Instant.now()));offers.save(copyOffer(find(offerId),type,ExecutionStatus.FAILED));}
    private Offer copyOffer(Offer o,PhaseType phase,ExecutionStatus status){return new Offer(o.id(),o.name(),o.customer(),o.language(),o.presentationLanguage(),o.inputDriveFolder(),o.outputDriveFolder(),o.presentationName(),o.aiProvider(),o.models(),o.presentationGuidance(),phase,status,o.createdAt(),Instant.now());}
    public record CreateOfferCommand(String name,String customer,String language,String presentationLanguage,String inputDriveFolder,String outputDriveFolder,String presentationName,String aiProvider,Map<String,String> models,Object presentationGuidance) {}
    static final class JsonFragments { private static final com.fasterxml.jackson.databind.ObjectMapper MAPPER=new com.fasterxml.jackson.databind.ObjectMapper(); static Map<String,String> parse(String raw){try{var start=raw.indexOf('{');var end=raw.lastIndexOf('}');if(start<0||end<=start)return Map.of("opportunityBrief",raw);var node=MAPPER.readTree(raw.substring(start,end+1));var out=new HashMap<String,String>();for(var key:List.of("opportunityBrief","questions","technology"))if(node.hasNonNull(key))out.put(key,node.get(key).asText());return out;}catch(Exception e){return Map.of("opportunityBrief",raw);}}}
}
