from datetime import datetime, timezone
from uuid import UUID
from sqlalchemy import delete, select
from sqlalchemy.ext.asyncio import AsyncSession
from agent_platform.domain import AgentConstraints, AgentDefinition, AgentError, AgentExecution, AgentUsage, ExecutionStatus, KnowledgeBase, KnowledgeChunk, KnowledgeDocument, KnowledgeDocumentStatus, ModelPolicy, SkillDefinition
from agent_platform.persistence.models import AgentCapabilityRecord, AgentKnowledgeScopeRecord, AgentRecord, AgentSkillRecord, AgentToolRecord, ExecutionEventRecord, ExecutionRecord, KnowledgeBaseRecord, KnowledgeChunkRecord, KnowledgeDocumentRecord, SkillRecord

def _agent_to_domain(r): return AgentDefinition(id=r.id,key=r.key,name=r.name,description=r.description,role=r.role,capabilities=[i.value for i in r.capabilities],skills=[i.skill_key for i in r.skills],knowledge_scopes=[i.scope_key for i in r.knowledge_scopes],allowed_tools=[i.tool_key for i in r.tools],model_policy=ModelPolicy.model_validate(r.model_policy or {}),constraints=AgentConstraints.model_validate(r.constraints or {}),version=r.version,enabled=r.enabled)
def _skill_to_domain(r): return SkillDefinition(id=r.id,key=r.key,name=r.name,description=r.description,objective=r.objective,instructions=r.instructions,inputs=r.inputs or [],output_schema=r.output_schema or {},knowledge_sources=r.knowledge_sources or [],allowed_tools=r.allowed_tools or [],constraints=r.constraints or {},version=r.version,enabled=r.enabled)
def _execution_to_domain(r): return AgentExecution(id=r.id,correlation_id=r.correlation_id,agent_key=r.agent_key,skill_key=r.skill_key,status=ExecutionStatus(r.status),objective=r.objective,runtime=r.runtime,model=r.model,started_at=r.started_at,completed_at=r.completed_at,created_at=r.created_at,usage=AgentUsage.model_validate(r.usage or {}),provider_request_id=r.provider_request_id,trace_id=r.trace_id,error=AgentError.model_validate(r.error) if r.error else None)
def _base_to_domain(r): return KnowledgeBase(id=r.id,key=r.key,name=r.name,description=r.description,metadata=r.metadata_json or {},enabled=r.enabled,created_at=r.created_at)
def _document_to_domain(r): return KnowledgeDocument(id=r.id,knowledge_base_key=r.knowledge_base_key,title=r.title,content=r.content,media_type=r.media_type,source_uri=r.source_uri,metadata=r.metadata_json or {},status=KnowledgeDocumentStatus(r.status),created_at=r.created_at)
def _chunk_to_domain(r): return KnowledgeChunk(id=r.id,document_id=r.document_id,ordinal=r.ordinal,content=r.content,metadata=r.metadata_json or {},embedding=list(r.embedding) if r.embedding is not None else None,embedding_model=r.embedding_model,created_at=r.created_at)

class PostgresAgentRepository:
    def __init__(self,session:AsyncSession): self.session=session
    async def list(self): result=await self.session.execute(select(AgentRecord).order_by(AgentRecord.key)); return [_agent_to_domain(r) for r in result.scalars().unique().all()]
    async def get_by_key(self,key): result=await self.session.execute(select(AgentRecord).where(AgentRecord.key==key)); r=result.scalars().unique().one_or_none(); return _agent_to_domain(r) if r else None
    async def create(self,a): self.session.add(AgentRecord(id=a.id,key=a.key,name=a.name,description=a.description,role=a.role,model_policy=a.model_policy.model_dump(mode="json"),constraints=a.constraints.model_dump(mode="json"),version=a.version,enabled=a.enabled,capabilities=[AgentCapabilityRecord(value=v) for v in a.capabilities],skills=[AgentSkillRecord(skill_key=v) for v in a.skills],tools=[AgentToolRecord(tool_key=v) for v in a.allowed_tools],knowledge_scopes=[AgentKnowledgeScopeRecord(scope_key=v) for v in a.knowledge_scopes])); await self.session.commit(); return a
    async def update(self,a): result=await self.session.execute(select(AgentRecord).where(AgentRecord.key==a.key)); r=result.scalars().unique().one(); r.name=a.name; r.description=a.description; r.role=a.role; r.model_policy=a.model_policy.model_dump(mode="json"); r.constraints=a.constraints.model_dump(mode="json"); r.version=a.version; r.enabled=a.enabled; r.capabilities=[AgentCapabilityRecord(value=v) for v in a.capabilities]; r.skills=[AgentSkillRecord(skill_key=v) for v in a.skills]; r.tools=[AgentToolRecord(tool_key=v) for v in a.allowed_tools]; r.knowledge_scopes=[AgentKnowledgeScopeRecord(scope_key=v) for v in a.knowledge_scopes]; await self.session.commit(); return a
class PostgresSkillRepository:
    def __init__(self,session:AsyncSession): self.session=session
    async def list(self): result=await self.session.execute(select(SkillRecord).order_by(SkillRecord.key)); return [_skill_to_domain(r) for r in result.scalars().all()]
    async def get_by_key(self,key): result=await self.session.execute(select(SkillRecord).where(SkillRecord.key==key)); r=result.scalar_one_or_none(); return _skill_to_domain(r) if r else None
    async def create(self,s): self.session.add(SkillRecord(id=s.id,key=s.key,name=s.name,description=s.description,objective=s.objective,instructions=s.instructions,inputs=s.inputs,output_schema=s.output_schema,knowledge_sources=s.knowledge_sources,allowed_tools=s.allowed_tools,constraints=s.constraints,version=s.version,enabled=s.enabled)); await self.session.commit(); return s
    async def update(self,s): result=await self.session.execute(select(SkillRecord).where(SkillRecord.key==s.key)); r=result.scalar_one(); r.name=s.name; r.description=s.description; r.objective=s.objective; r.instructions=s.instructions; r.inputs=s.inputs; r.output_schema=s.output_schema; r.knowledge_sources=s.knowledge_sources; r.allowed_tools=s.allowed_tools; r.constraints=s.constraints; r.version=s.version; r.enabled=s.enabled; await self.session.commit(); return s
class PostgresExecutionRepository:
    def __init__(self,session:AsyncSession): self.session=session
    async def get(self,execution_id): r=await self.session.get(ExecutionRecord,execution_id); return _execution_to_domain(r) if r else None
    async def create(self,e): self.session.add(ExecutionRecord(id=e.id,correlation_id=e.correlation_id,agent_key=e.agent_key,skill_key=e.skill_key,status=e.status.value,objective=e.objective,runtime=e.runtime,model=e.model,started_at=e.started_at,completed_at=e.completed_at,created_at=e.created_at,usage=e.usage.model_dump(mode="json"),provider_request_id=e.provider_request_id,trace_id=e.trace_id,error=e.error.model_dump(mode="json") if e.error else None)); await self.session.commit(); return e
    async def update(self,e): r=await self.session.get(ExecutionRecord,e.id); r.status=e.status.value; r.runtime=e.runtime; r.model=e.model; r.started_at=e.started_at; r.completed_at=e.completed_at; r.usage=e.usage.model_dump(mode="json"); r.provider_request_id=e.provider_request_id; r.trace_id=e.trace_id; r.error=e.error.model_dump(mode="json") if e.error else None; await self.session.commit(); return e
    async def add_event(self,execution_id,event_type,payload): self.session.add(ExecutionEventRecord(execution_id=execution_id,event_type=event_type,payload=payload,created_at=datetime.now(timezone.utc))); await self.session.commit()
    async def list_events(self,execution_id): result=await self.session.execute(select(ExecutionEventRecord).where(ExecutionEventRecord.execution_id==execution_id).order_by(ExecutionEventRecord.created_at)); return [{"event_type":r.event_type,"payload":r.payload,"created_at":r.created_at.isoformat()} for r in result.scalars().all()]
class PostgresKnowledgeRepository:
    def __init__(self,session:AsyncSession): self.session=session
    async def list_bases(self): result=await self.session.execute(select(KnowledgeBaseRecord).order_by(KnowledgeBaseRecord.key)); return [_base_to_domain(r) for r in result.scalars().all()]
    async def get_base(self,key): result=await self.session.execute(select(KnowledgeBaseRecord).where(KnowledgeBaseRecord.key==key)); r=result.scalar_one_or_none(); return _base_to_domain(r) if r else None
    async def create_base(self,item): self.session.add(KnowledgeBaseRecord(id=item.id,key=item.key,name=item.name,description=item.description,metadata_json=item.metadata,enabled=item.enabled,created_at=item.created_at)); await self.session.commit(); return item
    async def create_document(self,item): self.session.add(KnowledgeDocumentRecord(id=item.id,knowledge_base_key=item.knowledge_base_key,title=item.title,content=item.content,media_type=item.media_type,source_uri=item.source_uri,metadata_json=item.metadata,status=item.status.value,created_at=item.created_at)); await self.session.commit(); return item
    async def update_document(self,item):
        r=await self.session.get(KnowledgeDocumentRecord,item.id)
        if r is None: raise LookupError(f"Knowledge document '{item.id}' not found")
        r.title=item.title; r.content=item.content; r.media_type=item.media_type; r.source_uri=item.source_uri; r.metadata_json=item.metadata; r.status=item.status.value; await self.session.commit(); return item
    async def list_documents(self,key): result=await self.session.execute(select(KnowledgeDocumentRecord).where(KnowledgeDocumentRecord.knowledge_base_key==key).order_by(KnowledgeDocumentRecord.created_at)); return [_document_to_domain(r) for r in result.scalars().all()]
    async def get_document(self,document_id): r=await self.session.get(KnowledgeDocumentRecord,document_id); return _document_to_domain(r) if r else None
    async def replace_chunks(self,document_id,chunks):
        await self.session.execute(delete(KnowledgeChunkRecord).where(KnowledgeChunkRecord.document_id==document_id))
        self.session.add_all([KnowledgeChunkRecord(id=c.id,document_id=c.document_id,ordinal=c.ordinal,content=c.content,metadata_json=c.metadata,embedding=c.embedding,embedding_model=c.embedding_model,created_at=c.created_at) for c in chunks]); await self.session.commit(); return chunks
    async def list_chunks(self,document_id): result=await self.session.execute(select(KnowledgeChunkRecord).where(KnowledgeChunkRecord.document_id==document_id).order_by(KnowledgeChunkRecord.ordinal)); return [_chunk_to_domain(r) for r in result.scalars().all()]
