from typing import Protocol
from uuid import UUID

from agent_platform.domain import AgentDefinition, AgentExecution, SkillDefinition


class AgentRepository(Protocol):
    async def list(self) -> list[AgentDefinition]: ...
    async def get_by_key(self, key: str) -> AgentDefinition | None: ...
    async def create(self, agent: AgentDefinition) -> AgentDefinition: ...
    async def update(self, agent: AgentDefinition) -> AgentDefinition: ...


class SkillRepository(Protocol):
    async def list(self) -> list[SkillDefinition]: ...
    async def get_by_key(self, key: str) -> SkillDefinition | None: ...
    async def create(self, skill: SkillDefinition) -> SkillDefinition: ...
    async def update(self, skill: SkillDefinition) -> SkillDefinition: ...


class ExecutionRepository(Protocol):
    async def get(self, execution_id: UUID) -> AgentExecution | None: ...
    async def create(self, execution: AgentExecution) -> AgentExecution: ...
    async def add_event(self, execution_id: UUID, event_type: str, payload: dict) -> None: ...
    async def list_events(self, execution_id: UUID) -> list[dict]: ...
