from typing import Protocol
from uuid import UUID
from agent_platform.domain import AgentDefinition, AgentExecution, KnowledgeBase, KnowledgeChunk, KnowledgeDocument, SkillDefinition

class AgentRepository(Protocol):
    async def list(self) -> list[AgentDefinition]: ...
    async def get_by_key(self, key: str) -> AgentDefinition | None: ...
    async def create(self, agent: AgentDefinition) -> AgentDefinition: ...
    async def update(self, agent: AgentDefinition) -> AgentDefinition: ...
class SkillRepository(Protocol):
    async def list(self) -> list[SkillDefinition]: ...
    async def get_by_key(self, key: str) -> SkillDefinition | None: ...
    async def create(self, skill: SkillDefinition) -> SkillDefinition: ...
    async def update(self, skill: SkillDefinition) -> SkillDefinition: ...
class ExecutionRepository(Protocol):
    async def get(self, execution_id: UUID) -> AgentExecution | None: ...
    async def create(self, execution: AgentExecution) -> AgentExecution: ...
    async def update(self, execution: AgentExecution) -> AgentExecution: ...
    async def add_event(self, execution_id: UUID, event_type: str, payload: dict) -> None: ...
    async def list_events(self, execution_id: UUID) -> list[dict]: ...
class KnowledgeRepository(Protocol):
    async def list_bases(self) -> list[KnowledgeBase]: ...
    async def get_base(self, key: str) -> KnowledgeBase | None: ...
    async def create_base(self, item: KnowledgeBase) -> KnowledgeBase: ...
    async def create_document(self, item: KnowledgeDocument) -> KnowledgeDocument: ...
    async def update_document(self, item: KnowledgeDocument) -> KnowledgeDocument: ...
    async def list_documents(self, knowledge_base_key: str) -> list[KnowledgeDocument]: ...
    async def get_document(self, document_id: UUID) -> KnowledgeDocument | None: ...
    async def list_versions(self, family_id: UUID) -> list[KnowledgeDocument]: ...
    async def delete_document(self, document_id: UUID) -> None: ...
    async def replace_chunks(self, document_id: UUID, chunks: list[KnowledgeChunk]) -> list[KnowledgeChunk]: ...
    async def list_chunks(self, document_id: UUID) -> list[KnowledgeChunk]: ...
